### ISSUE TITLE
Group all selected files into a single request

### ISSUE THREAD

**Issue by Pooyahmti** [files-ui/files-ui-react#32]
Currently after file selection when Upload action button is clicked files are sent one after another each one in a separate request.
Is it possible to configure the component to group all files in a single request  and send to server ?

**Comment by Drezir** [comment]
I did it by using custom button

**Comment by Pooyahmti** [comment]
> I did it by using custom button

Yes that is easy to implement the problem is the preview part but I'm working on it if you are interested we can collaborate cause the developer seems inactive.
