### ISSUE TITLE
double click on FileMosaic opens an alert

### ISSUE THREAD

**Issue by JuanPabloOS** [files-ui/files-ui-react#5]
**Describe the bug**
When double clicking on the FileMosaic an alert will show with the text "double click on file", I provided my own onDoubleClick to the component, but it doesn't override the default function but I'm still able to call my custom function.

**To Reproduce**
1. Render this code
`<Dropzone
              onChange={updateFiles}
              value={files}
              accept=".csv"
              maxFiles={1}
            >
              {files.map((file: ExtFile) => (
                <FileMosaic
                  key={file.id}
                  {...file}
                  onDelete={removeFile}
                  info={true}
                  onDoubleClick={() => {
                    console.log("hi there");
                  }}
                />
              ))}
            </Dropzone>`
3. upload something in the dropzone
4. double click on the FileMosaic
5. An alert will show up with the text "double click on file"

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/42472823/228652314-e8f43308-8bb0-4526-be26-621a2ba8eeec.png)

I'm using @files-ui/react: 1.0.5

**Comment by JinSSJ3** [comment]
Hi @JuanPabloOS, thanks for the alert.

We are sorry for the inconvenience. 
Could you please upgrade to [@files-ui/react 1.0.8](https://www.npmjs.com/package/@files-ui/react/v/1.0.8)?
That's the latest version in which we have already solved this issue.

Please, tell us if that worked for you:
Thanks in advance! 🎆

**Comment by JinSSJ3** [comment]
Hey @JuanPabloOS , we hope you solved the problem by updating the library. 🚀 
If not, feel free to open the issue again!

Sincerely.

**Comment by JuanPabloOS** [comment]
Hi guys, thank you very much for the support!
